version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: cd back && npm install
            - run: npm test && cd ..
            - run: cd client && yarn
            - run: yarn build && cd ..
workflows:
    build-and-test:
      jobs:
        - build-and-test
