version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - restore_cache:
          key: node-modules-cache-{{ checksum "back/package-lock.json" }}
      - run: cd back && yarn install
      - run: cd back && yarn test
      - save_cache:
                key: node-modules-cache-{{ checksum "back/package-lock.json" }}
                paths:
                  - back/node_modules
      - restore_cache:
                key: node-modules-cache-{{ checksum "client/yarn.lock" }}
      - run: cd client && yarn
      - run: cd client && yarn build
      - save_cache:
                key: node-modules-cache-{{ checksum "client/yarn.lock" }}
                paths:
                  - client/node_modules
workflows:
    build-and-test:
      jobs:
        - build-and-test
