version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/default:
          steps:
            - run: cd back && npm install
            - run: cd back && npm test
            - run: cd client && yarn
            - run: cd client && yarn build
workflows:
    build-and-test:
      jobs:
        - build-and-test
