version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - restore_cache:
          key: node-modules-cache-{{ checksum "back/package-lock.json" }}
      - run: cd back && yarn install
      - run: cd back && yarn test
      - save_cache:
                key: node-modules-cache-{{ checksum "back/package-lock.json" }}
                paths:
                  - back/node_modules
      - restore_cache:
                key: node-modules-cache-{{ checksum "client/yarn.lock" }}
      - run: cd client && yarn
      - run: cd client && yarn build
      - save_cache:
                key: node-modules-cache-{{ checksum "client/yarn.lock" }}
                paths:
                  - client/node_modules
  deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "64:23:40:6a:5e:3b:f7:97:fb:d3:49:4b:76:06:78:4a"
      - run:
        name: Deploy over SSH
        command: |
          ssh root@51.255.174.48 "cd iot && ./deploy.sh"

workflows:
    build-and-test-and-deploy:
      jobs:
        - build-and-test
        - deploy:
            requires:
              - build-and-test
            filters:
              branches:
                only: master