version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - restore_cache:
          key: node-modules-cache-{{ checksum "back/package-lock.json" }}
      - run: cd back && yarn install
      - save_cache:
                key: node-modules-cache-{{ checksum "back/package-lock.json" }}
                paths:
                  - back/node_modules
      - restore_cache:
                key: node-modules-cache-{{ checksum "client/yarn.lock" }}
      - run: cd client && yarn
      - save_cache:
                key: node-modules-cache-{{ checksum "client/yarn.lock" }}
                paths:
                  - client/node_modules
  deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "70:51:cf:a0:af:51:af:b2:59:57:82:73:17:70:5e:57"
      - run:
          name: Deploy over SSH
          command: ssh root@51.255.174.48 "cd iot && ./deploy.sh"

workflows:
    build-and-test-and-deploy:
      jobs:
        - build-and-test
        - deploy:
            requires:
              - build-and-test
            filters:
              branches:
                only: master